Repository sfsu-csc-667-fall-2024-roberts/term-project-codingblocks, pull requests merged in 2024-12, with the labels that each got.

#26 DB Instructions
  README.md
Labels: documentation

#24 Implement Database + Migrations
  migrations/1733212754134_users-table.ts
  migrations/1733212761378_games-table.ts
  migrations/1733212906617_game-users.ts
  package.json
  pg/CodingBlocks.png
  pg/db.sql
  src/server/db/users/index.ts
  src/server/routes/auth.ts
Labels: feature

#27 Issue #25 first draft
  src/server/db/games/index.ts
  src/server/db/games/sql.ts
  src/server/middleware/games.ts
  src/server/routes/lobby.ts
Labels: feature

#30 Implement Basic Web Sockets
  package-lock.json
  package.json
  src/server/config/index.ts
  src/server/config/session.ts
  src/server/config/sockets.ts
  src/server/index.ts
Labels: feature

#35 Implement Additional Database Entries
  migrations/1734236602788_game-current-players.ts
  migrations/1734236672292_game-turn-state.ts
  migrations/1734238030708_game-cards.ts
  migrations/1734238674986_game-users-count-code.ts
  migrations/1734238728566_cards-table.ts
  migrations/1734238851326_game-cards-pile.ts
  src/server/db/games/index.ts
  src/server/db/index.ts
  src/server/routes/lobby.ts
Labels: feature

#36 Implement game view routes
  src/server/db/games/index.ts
  src/server/routes/games.ts
  src/server/routes/lobby.ts
  src/server/views/games/game.ejs
Labels: feature, fix

#37 Implement middleware for games route
  src/server/routes/game-middleware/game-update.ts
  src/server/routes/game-middleware/index.ts
  src/server/routes/game-middleware/player-draw.ts
Labels: feature

#38 Game Middleware Hotfix
  src/server/db/games/index.ts
  src/server/db/games/sql.ts
  src/server/routes/game-middleware/index.ts
  src/server/routes/game-middleware/is-player-turn.ts
Labels: feature, fix

#39 doc: update readme with db instructions
  README.md
Labels: documentation

#40 Home redirect fix
  src/server/routes/home.ts
  src/server/routes/lobby.ts
  src/server/routes/root.ts
  src/server/views/games/lobby.ejs
  src/server/views/home.ejs
Labels: feature, fix, refactor

#43 Initial Game Actions
  migrations/1733212754134_users-table.ts
  migrations/1733212761378_games-table.ts
  migrations/1733212906617_game-users.ts
  migrations/1734236672292_game-turn-state.ts
  migrations/1734238030708_game-cards.ts
  migrations/1734238674986_game-users-count-code.ts
  migrations/1734238728566_cards-table.ts
  migrations/1734238851326_game-cards-pile.ts
  pg/db.sql
  src/client/games.ts
  src/public/js/games.js
  src/server/db/games/index.ts
  src/server/db/games/sql.ts
  src/server/routes/game-middleware/index.ts
  src/server/routes/game-middleware/player-draw.ts
  src/server/routes/game-middleware/player-in-game.ts
  src/server/routes/games.ts
  src/server/views/games/game.ejs
  src/server/views/games/join.ejs
  webpack.config.ts
Labels: feature, fix, refactor

#45 Robust Game Actions + Game Flow
  migrations/1734409109110_game-cards.ts
  src/client/games.ts
  src/client/games/index.ts
  src/client/games/update-game.ts
  src/client/main.ts
  src/client/types.ts
  src/public/js/games.js
  src/public/js/main.js
  src/server/db/games/index.ts
  src/server/db/games/sql.ts
  src/server/routes/games.ts
  src/server/views/games/game.ejs
  src/server/views/games/winner.ejs
Labels: feature, fix

#46 Implement Chat Backend
  src/server/index.ts
  src/server/middleware/chat.ts
  src/server/middleware/index.ts
  src/server/routes/chat.ts
  src/server/routes/index.ts
Labels: feature

#47 Implement updating game view through sockets
  src/client/games.ts
  src/client/games/update-game.ts
  src/client/types.ts
  src/public/js/games.js
  src/server/routes/game-middleware/game-update.ts
  src/server/routes/games.ts
  src/server/views/games/game.ejs
Labels: feature, fix

#51 Hotfix winner redirect
  src/client/games/update-game.ts
  src/public/js/games.js
Labels: fix

#52 Format
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
  src/server/views/authenticated.ejs
  src/server/views/games/game.ejs
  src/server/views/games/join.ejs
  src/server/views/games/winner.ejs
  src/server/views/home.ejs
  src/server/views/partials/navbar.ejs
  src/server/views/root.ejs
  src/server/views/unauthenticated.ejs
  weekly-reports/week-3/README.md
Labels: chore

#53 Implement Lobby System
  .gitignore
  src/public/js/games.js
  src/public/js/main.js
  src/public/stylesheets/style.css
  src/server/db/games/index.ts
  src/server/db/games/sql.ts
  src/server/routes/lobby.ts
  src/server/views/games/lobby.ejs
Labels: feature

#54 Implement Chat partial
  src/client/chat.ts
  src/public/stylesheets/style.css
  src/server/views/games/game.ejs
  src/server/views/partials/chat.ejs
  webpack.config.ts
Labels: feature

#55 Implement basic winning hand logic
  src/server/db/games/hand.ts
  src/server/db/games/index.ts
Labels: feature, fix

#56 refactor: move head as partial
  src/server/views/auth/login.ejs
  src/server/views/auth/register.ejs
  src/server/views/games/game.ejs
  src/server/views/games/lobby.ejs
  src/server/views/partials/head.ejs
Labels: refactor

#57 Implement Lobby Names + Max Players
  migrations/1734684411488_games-name-maxplayers.ts
  src/server/db/games/index.ts
  src/server/db/games/sql.ts
  src/server/routes/lobby.ts
  src/server/views/games/game.ejs
  src/server/views/games/lobby.ejs
Labels: feature, fix

#58 Various Hotfixes for Demo Video
  src/client/games.ts
  src/client/games/update-game.ts
  src/server/db/games/sql.ts
  src/server/routes/games.ts
  src/server/views/games/game.ejs
  src/server/views/games/lobby.ejs
  src/server/views/games/winner.ejs
Labels: fix
