Repository sfsu-csc-667-fall-2024-roberts/term-project-codingblocks, pull requests merged in 2024-11, with the labels that each got.

#7 Initial Webpack Config
  package-lock.json
  package.json
  webpack.config.ts
Labels: feature

#8 Integeration of frontend with backend.
  package-lock.json
  package.json
  src/client/main.ts
  src/public/js/main.js
  src/server/config/index.ts
  src/server/config/livereload.ts
  src/server/index.ts
  src/server/views/root.ejs
Labels: feature

#9 Prettier chore
  .husky/pre-commit
  package.json
Labels: chores

#10 Implemented basic API endpoints
  package.json
  src/server/index.ts
  src/server/routes/auth.ts
  src/server/routes/lobby.ts
  src/server/views/authenticated.ejs
  src/server/views/unauthenticated.ejs
  webpack.config.ts
Labels: feature

#18 Hotfix missing routes
  src/server/index.ts
  src/server/routes/games.ts
  src/server/routes/home.ts
  src/server/routes/index.ts
Labels: bug, fix, chore

#19 Hotfix duplicate calls to configureLiveReload()
  package.json
  src/server/index.ts
Labels: bug, fix

#20 Basic Database Connection + Queries
  package-lock.json
  package.json
  src/server/db/connection.ts
  src/server/db/index.ts
  src/server/db/users/index.ts
  src/server/db/users/sql.ts
Labels: feature

#21 fix: re-correct placement for liveReload initialization
  src/server/index.ts
Labels: fix, chore

#22 Fix to the auth and session. Also, routes are fixed.
  package-lock.json
  package.json
  src/public/stylesheets/style.css
  src/server/.DS_Store
  src/server/config/index.ts
  src/server/config/livereload.ts
  src/server/config/session.ts
  src/server/index.ts
  src/server/middleware/authentication.ts
  src/server/routes/auth.ts
  src/server/routes/home.ts
  src/server/routes/lobby.ts
  src/server/views/auth/login.ejs
  src/server/views/auth/register.ejs
  src/server/views/authenticated.ejs
  src/server/views/games/lobby.ejs
  src/server/views/home.ejs
  src/server/views/partials/navbar.ejs
Labels: feature, fix
